### ISSUE TITLE
[mzml] `decode_binary` argument documented but not implemented

### ISSUE THREAD

**Issue by RalfG** [levitsky/pyteomics#104]
Hi everyone,

In the mzml reader documentation for `read`, the `decode_binary` argument is listed, but it does not seem to be implemented. Setting the argument results in a TypeError:
```
TypeError: read() got an unexpected keyword argument 'decode_binary'
```

Documentation:
https://github.com/levitsky/pyteomics/blob/7c7971d468394a1844059a0af605111e515c25b2/pyteomics/mzml.py#L387-L390

Function definition:
https://github.com/levitsky/pyteomics/blob/7c7971d468394a1844059a0af605111e515c25b2/pyteomics/mzml.py#L360

I guess the documentation is a left-over from previous functionality?

Best,
Ralf

**Comment by mobiusklein** [comment]
I think this got copied over from the `MzML` init itself, which `read` is just a wrapper for. We can add a pass through, but in the interim just call `mzml.MzML` if you want to use that functionality?
