### ISSUE TITLE
Pandas is now a hard requirement

### ISSUE THREAD

**Issue by mobiusklein** [levitsky/pyteomics#119]
The fix to #118 made `pandas` a hard requirement, no longer optional behind the `DF` feature. Is this desirable? I don't use the `DF` feature myself, but it clearly has uses. It also makes `numpy` a mandatory dependency too, but there's no getting around that.

The net result is that if you install `pyteomics` without the `DF` feature enabled in a fresh virtual environment, it will not install `pandas` and then importing `pyteomics` modules that depend upon `pyteomics.auxiliary.target_decoy` the program crashes.

**Comment by levitsky** [comment]
Looks like I missed the fact that the `patch` import not only patched the method but also handled a possible `ImportError`.  Should I just add a try/except in `target_decoy.py` around the `pandas` import?

**Comment by mobiusklein** [comment]
Apologies for the terseness of the post. Catching the import error around the `import pandas` line and setting `pd = None` should be enough.

What I meant about `numpy` is that if it was your intent to make `pandas` a hard requirement, then it would also mean we would remove the `numpy` optional feature too. But since `numpy` is so ubiquitous it's been ported to several other Python implementations.

**Comment by levitsky** [comment]
Thank you. As far as I understand, this should now be fixed.
