### ISSUE TITLE
Add a __version__ method to pyteomics

### ISSUE THREAD

**Issue by sugatoray** [levitsky/pyteomics#13]
Typically python packages have a *dunder* method for version: `package.__version__`. 

It helps to check and log the version of the package under use in an analysis. However, I could not find any such `pyteomics.__version__` method to access the version. I see that you have a file `VERSION` in the repo and the `setup.py` file accesses the current version information from here.

Please add a `pyteomics.__version__` method to dynamically provide the version of the package.

If however, I have missed out on something or am mistaken please let me know.

Thank you.

**Comment by levitsky** [comment]
Hi, thank you for the feedback!

Indeed, there is no method or attribute that captures the current version in pyteomics. It should be fairly easy to add one for convenience.

However, version info can be extracted fairly easily in Python, like with any other package. See e.g. this [answer on SO](https://stackoverflow.com/a/32965521/1258041).

Demo:

```
In [1]: import pkg_resources

In [2]: pkg_resources.get_distribution('pyteomics').version
Out[2]: '4.4.0.dev1'
```
Also, on Python 3.8 and newer:
```
In [1]: from importlib.metadata import version

In [2]: version('pyteomics')
Out[2]: '4.4.0.dev1'
```

**Comment by levitsky** [comment]
Looking more into this, I find that I cannot easily add anything to `pyteomics/__init__.py`, as Pyteomics is a [namespace package](https://packaging.python.org/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages). Best I can do then is make it available under `pyteomics.auxiliary` (which is not as easy to find) or perhaps create a module called `pyteomics.version`. Does anyone have any suggestions? @sugatoray @mobiusklein

**Comment by mobiusklein** [comment]
I think a `pyteomics.version` submodule is probably the safest and cleanest way if we want to support this without requiring the user import the those tools (not that we can't try to import and use them ourselves to get it). The top-level module having a `__version__` attribute is convenient.

If there absolutely *has to* be a `__version__` attribute on `pyteomics`, we can force that to happen **if** the user imports at least one submodule first, and then  have submodules import the following monkey-patching module
```python
import sys
import pkg_resources
version = pkg_resources.get_distribution('pyteomics').version
sys.modules['pyteomics'].__version__ = version
```
But this would lead to unexpected behavior when the user just tries to read that attribute off a top-level import of `pyteomics` alone.

**Comment by sugatoray** [comment]
I tried to find a repo that has some similarity to `pyteomics`. Though I am not sure if it is a good example or not, I would suggest you take a look at [`mendley` repo][#mendley-github] as an alternative.

They also use a version file ([`version.py`][#mendley-github]) that introduces a `package.__version__` attribute.

[#mendley-github]: https://github.com/Mendeley/mendeley-python-sdk/blob/master/mendeley/version.py
