### ISSUE TITLE
Incorrect expasy rule

### ISSUE THREAD

**Issue by Karl-Krauth** [levitsky/pyteomics#135]
This rule for thermolysin is incorrect: https://github.com/levitsky/pyteomics/blob/66dcd9d6d35e20c39e82c6c408e1b8ed05089ea6/pyteomics/parser.py#L844

it should be: `r'[^DE](?=[AFILMV][^P])'`
If you check the summary of the cleavage rules here: https://web.expasy.org/peptide_cutter/peptidecutter_enzymes.html the `[^P]` condition isn't included but it's included in the text above it and also seems to be implemented in their perl script.

I haven't checked other enzymes but there might be similar errors there too.

**Comment by levitsky** [comment]
Thank you for reporting. I made the change you proposed, seeing as the Proline effect is mentioned both in text and in the tool itself.
