### ISSUE TITLE
Unparsable modifications are silently ignored in ProForma mass calculation

### ISSUE THREAD

**Issue by caetera** [levitsky/pyteomics#157]
Hello,

I discovered a quirky "attitude" of ProForma parsing.

If a ProForma object has a modification that cannot be decoded this modification is silently ignored in all further calculations, while the same calculation on the modification object raises. I believe it will be better to propagate the Exception rather than silencing it.

Here is an example (Pyteomics 4.7.2 Python 3.10.2 Win64)

Both raise `KeyError`

```python
proforma.GenericModification('Generic').mass

proforma.UnimodModification('123456').mass
```

However - this works while ignoring the modification

```python
for peptide in ['PEPTIDE', 'PEPTID[Generic]E', 'PEPTID[UNIMOD:123456]E']:
    prof = proforma.ProForma.parse(peptide)
    print(f'{prof}\n{prof.mass}\n')
```
```
PEPTIDE
799.3599640267099

PEPTID[Generic]E
799.3599640267099

PEPTID[UNIMOD:123456]E
799.3599640267099
```

**Comment by mobiusklein** [comment]
This is likely an oversight on my part. I'll investigate why I silenced the exceptions in `ProForma` methods.
