### ISSUE TITLE
Correct precursor m/z accession ID?

### ISSUE THREAD

**Issue by rcatzel** [levitsky/pyteomics#160]
Hi there,

I am writing a method to read in an mzml file as part of a de novo peptide sequencing pipeline, and am using the controlled vocabulary functionality documented [here](https://pyteomics.readthedocs.io/en/latest/data.html#controlled-vocabulary-terms-in-structured-data). I was wondering what the correct precursor m/z accession number to use was as these "MS:1000040", "MS:1000827", "MS:1000744" seem to be similar to me, but I am new to the field. If they are interchangeable then I will allow any of these accession IDs to be mapped to the precursor m/z. Are there cases where these accession IDs are not interchangeable? If they are not interchangeable, which ID is most correct to use?

On a similar note, I am unsure of what accession ID to use for a peptide sequence, in the case that it is included in the mzml file. Is "MS:1000889" correct? 

Thanks very much.

**Comment by levitsky** [comment]
Hi @rcatzel,

I can't say a whole lot for certain, but `MS:1000040` appears to be basically a unit accession for everything measured in m/z units, and the other two are commonly seen present and with identical values. I don't know of specific use cases when there is a difference, perhaps @mobiusklein would have more insight.

**Comment by rcatzel** [comment]
Thanks!
