### ISSUE TITLE
tandem is_decoy function

### ISSUE THREAD

**Issue by tivdnbos** [levitsky/pyteomics#2]
Dear all,

I am using Tandem XML files where the decoy  proteins are indicated as follows: 
`protein: [{ (...), 'label': 'tr|B0MJG7_REVERSED|B0MJG7_REVERSED_9FIRM Selenium-dependent molybdenum hydroxylase...', 'note': 'tr|B0MJG7_REVERSED|B0MJG7_REVERSED_9FIRM Selenium-dependent molybdenum hydroxylase 1 OS=Anaerostipes caccae DSM 14662 GN=ANACAC_03779 PE=4 SV=1' , (...)}]`.

Therefore, I would like to write a is_decoy function, but Iḿ not sure what to pass by. This could be a lambda expression or boolean evaluation?

Thanks for helping me out!

**Comment by levitsky** [comment]
Hi,

If you are using `tandem.filter`, then indeed you need to provide your own function (or lambda). It can look like this:

`result = tandem.filter(..., is_decoy=lambda psm: all('_REVERSED_' in prot['label'] for prot in psm['protein']))`

**Comment by tivdnbos** [comment]
Thanks a lot for the quick response!

All the best,
Tim
