### ISSUE TITLE
After using  ms_data = mzxml.MzXML(filename) the file stays open on Windows.

### ISSUE THREAD

**Issue by soerendip** [levitsky/pyteomics#25]
I wonder if I have to call some method to close the file? On Linux I did not experience any trouble, but on Windows processed files cannot be deleted. 

I open the file with 

    ms_data = mzxml.MzXML(fn)

And then iterate through the data to generate a pandas dataframe. Then the data is stored in a different format. 

```
while True:
        try:
            data = ms_data.next()     
            df = pd.DataFrame({col: np.array(data[col]) for col in cols} )
            slices.append( df )
        except:         
            break 
```
            
How can I close the file again? I looked in the documentation, but did not find a related method.

**Comment by levitsky** [comment]
Hi! This aspect is consistent with how you work with files.

Accordingly, there is a `.close()` method on all readers. You should be able to do:

    ms_data.close()

Alternatively, you can use the `with` syntax, e.g.:

```
with mzxml.MzXML(fn) as ms_data:
    for data in ms_data:
         df = pd.DataFrame({col: np.array(data[col]) for col in cols})
         slices.append( df )
```

**Comment by levitsky** [comment]
Hi @soerendip, was I able to answer your question?

**Comment by soerendip** [comment]
Yes, thank you. I had not seen the  .close() method in the docs, but it makes total sense :-)

**Comment by levitsky** [comment]
Thanks! For reference, the `.close()` method is mentioned in the docs here: https://pyteomics.readthedocs.io/en/latest/data.html#general-notes.
