### ISSUE TITLE
Pyteomics fails to parse mzId files with <Fragmentation> information

### ISSUE THREAD

**Issue by jgriss** [levitsky/pyteomics#33]
Hi,

First of all, thanks a lot for this great library!

I recently found that pyteomics can't open mzId files created using [PeptideShaker](https://github.com/compomics/peptide-shaker). Iterating of the SpectrumIdentificationResult objects never starts without significant CPU usage.

After I manually removed the `<Fragmentation>[...]</Fragmentation>` tags from the file, everything worked fine.

Kind regards,
Johannes

**Comment by mobiusklein** [comment]
Can you share the original mzIdentML file please? Or a reduced version if it is too large?

**Comment by jgriss** [comment]
Hi @mobiusklein 

You can download the file here (it's too big for GitHub):

https://cloudius.meduniwien.ac.at/index.php/s/zt7lZBf4VMTMbwT

Creating the MzIdentML object works. But as soon as I start iterating over it, the iteration never starts.

Thanks a lot for the help!

Kind regards,
Johannes

**Comment by mobiusklein** [comment]
@jgriss could you please try the branch in PR #34? It should fix your issue.
