### ISSUE TITLE
Warning is triggered even with `use_index=False`

### ISSUE THREAD

**Issue by hguturu** [levitsky/pyteomics#52]
https://github.com/levitsky/pyteomics/blob/1ef7a0972934cbafbee32df9f2a635a04502d9b1/pyteomics/auxiliary/file_helpers.py#L918

Is there a way to avoid this warning? I am passing a `seekable`, non-binary file handle and `use_index=False`. Specifically a `smart_open.open` object. It doesn't have a `mode` attribute when opening `s3` objects. It works, just was wondering if I can suppress the warning since the warning doesn't seem to match the issue.

**Comment by mobiusklein** [comment]
You shouldn't need to worry in your case. This is situation probably needs to be fixed with an `unset` value to handle default behavior more precisely.

**Comment by levitsky** [comment]
Thanks for reporting. This checking logic is taking me a lot of attempts to get right.
Does the current master behave as expected?

**Comment by hguturu** [comment]
I was  triggering this error on `4.4.2`. 

Using a master, it looks like the warning is suppressed for `use_index=False`, shows warning for `use_index=True`, but it errors out with `use_index=True`, where it tried to load an `IndexedFASTA` and I have a regular `FASTA`. I believe this how it should work?

**Comment by levitsky** [comment]
I think so! Thank you.
