### ISSUE TITLE
ThreadPool in PROXIAggregator not closed

### ISSUE THREAD

**Issue by bittremieux** [levitsky/pyteomics#66]
The `PROXIAggregator` uses a `ThreadPool` to query multiple PROXI resources simultaneously. This `ThreadPool` is [stored between multiple function calls](https://github.com/levitsky/pyteomics/blob/master/pyteomics/usi.py#L304), I assume to avoid the overhead of creating the `ThreadPool`. However, it is never properly closed, resulting in the following error:

```
Exception ignored in: <function Pool.__del__ at 0x7fe660d174c0>
Traceback (most recent call last):
File "/home/wout/.conda/envs/spectrum_utils/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
File "/home/wout/.conda/envs/spectrum_utils/lib/python3.9/multiprocessing/queues.py", line 372, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```

This does not interfere with my code, as it only happens at the end, presumably when all objects are cleaned up. However, it would be nice to avoid having this error at all.

Maybe the `ThreadPool` should just be created for resolving of individual USIs, and then immediately cleaned up? The overhead of repeatedly creating the pool should be pretty minimal, especially compared to REST API calls.

**Comment by mobiusklein** [comment]
I've added PR #67 to implement that behavior. The previous behavior is available if the `ephemeral_pool` attribute is set to `False` (now `True` by default).

It's hard to reproduce the message since it seems to be sensitive to the order in which some standard library modules are destroyed during interpreter shutdown.

**Comment by bittremieux** [comment]
Looks like a good fix. Thanks!
