### ISSUE TITLE
How to convert the modified scans into an mzXML file?

### ISSUE THREAD

**Issue by Mnago** [levitsky/pyteomics#72]
Hi,

`from pyteomics import mzxml
reader=mzxml.read(mzXML_file)
scans=[scan for scan in reader] 
`
We used pyteomics to get all scans information from the mzXML file which was converted by proteowizard. 
Then, we do some modifications to those scans and export them into a .csv file.
Is there any function to convert the modified scans into an mzXML file?

Best regards,

Winnie

**Comment by levitsky** [comment]
Hi!
There is no such function in Pyteomics. What could be helpful to you is @mobiusklein's [`psims`](https://github.com/mobiusklein/psims), which provides an API to write mzML. Perhaps you can convert that to mzXML then.
If you don't care about metadata at all, you could probably use [`pyteomics.mgf.write`](https://pyteomics.readthedocs.io/en/latest/api/mgf.html#pyteomics.mgf.write) and then convert MGF to mzXML.
