### ISSUE TITLE
Is there an idXML writer anywhere? what about a schema? 

### ISSUE THREAD

**Issue by trishorts** [levitsky/pyteomics#73]
I'd like to be able to generate an idXML from our own software but looking for an examples so that i can get it right. Is there test code to see if the files I generated are readable? other than using your reader and seeing if it crashes?

**Comment by levitsky** [comment]
Unfortunately I don't know much about this; I'd look at pyOpenMS to see if it provides a writing interface. There are also some schemas there: https://github.com/OpenMS/OpenMS/tree/develop/share/OpenMS/SCHEMAS

Unfortunately, with Pyteomics I didn't go any further than providing a reader.

**Comment by trishorts** [comment]
thank you!
