### ISSUE TITLE
tandem.DataFrame fails when tandem was run on .cmn input

### ISSUE THREAD

**Issue by kesinger** [levitsky/pyteomics#74]
When x!tandem is run on a file in 'common' format (https://www.thegpm.org/common/index.html) it appears to produce slightly different XML.  In particular, there is no 'note' tag inside the 'fragment ion mass spectrum', so the access here: https://github.com/levitsky/pyteomics/blob/master/pyteomics/tandem.py#L326 
fails.

If I use tandem.read instead, it appears to work.

**Comment by levitsky** [comment]
Thanks for reporting! If you can try the latest `master`, hopefully the issue is solved.

**Comment by kesinger** [comment]
Seems to work.  Thanks!
