### ISSUE TITLE
Add installatoin instructions for pyteomics for conda from the bioconda channel

### ISSUE THREAD

**Issue by fabianegli** [levitsky/pyteomics#88]
It would be great to also promote the possibility to install via bioconda, athough now the version on bioconda is not the latest (4.5.5 in bioconda instead of 4.5.6 on PyPI). Would a PR be welcome to add these installation instructions?

**Comment by levitsky** [comment]
A PR would be welcome!
The installation instructions reside in [INSTALL](https://github.com/levitsky/pyteomics/blob/master/INSTALL).

**Comment by fabianegli** [comment]
@levitsky Would you mind if I restructure the Installation instructions? I am tempted to remove OS specific language and reduce it to installations with `pip` and `conda` and link to the instructions to the respective tooling. But I am also happy to just add a conda related section at the end.

**Comment by levitsky** [comment]
Separate Windows instructions don't make a lot of sense to me, but mentioning alternative installation sources like AUR doesn't hurt IMHO. What do you think?

**Comment by fabianegli** [comment]
I am not familiar with AUR - and can't form a serious opinion on wether it is useful or not. I just think the installation instructions for package management tools can be deferred the tools themselves.

Additional notes/questions:

- Some URLs are still http instead of https which is supported on all linked websites in the INSTALL file.
- I find suggesting to use sudo for the installation of a python package disturbing and would like to remove it together with Ubuntu specific instructions.
- The docs say all dependencies are optional - but the installation instructions say that the dependencies should be installed and explicitly lists some in the pip install command. I am a bit confused as to how optional these dependencies are.

**Comment by levitsky** [comment]
- [ ] I am all for updating the URLs.
- [ ] Ubuntu-specific and Windows-specific instructions can be removed.
- [ ] Dependencies *are* optional. We can just leave `pip install pyteomics` there.
- [ ] The list of those dependencies is not complete and should be extended. There are also `spectrum_utils`, `h5py`,`hdf5plugin`, `psims`.
- [ ] Speaking of which, perhaps we should document the *extras* as defined in [setup.py](https://github.com/levitsky/pyteomics/blob/master/setup.py#L35-L43).

**Comment by levitsky** [comment]
I went ahead and implemented the rest of the items we discussed. @fabianegli please feel free to improve or comment!

**Comment by fabianegli** [comment]
Cool! I think you covered it all. 🥳
